version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/deal_in_api
    ports:
      - 8000:8000
    image: deal_in:deal_in_api
    container_name: deal_in_api_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=deal_in_tb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    container_name: postgres_db
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=rizky@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=rizky
    ports:
      - "5050:80"