# Generated by Django 3.1.7 on 2021-07-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal_in_tb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbldocuments',
            old_name='id',
            new_name='nik',
        ),
    ]
