# Generated by Django 3.1.7 on 2021-07-18 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal_in_tb', '0006_auto_20210718_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbltransaction',
            name='id_cart',
        ),
        migrations.RemoveField(
            model_name='tbltransaction',
            name='qty',
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='api_key',
            field=models.CharField(default='dbOJPTFYucAHbPygRnqevSjlnRPhdqpqkOHgXPvUAzxg38iD7a', max_length=50),
        ),
        migrations.CreateModel(
            name='TblDataTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('deleted', models.CharField(default=0, max_length=2)),
                ('id_item', models.ForeignKey(db_column='id_item', on_delete=django.db.models.deletion.DO_NOTHING, to='deal_in_tb.tblitem')),
                ('id_trans', models.ForeignKey(db_column='id_trans', on_delete=django.db.models.deletion.DO_NOTHING, to='deal_in_tb.tbltransaction')),
            ],
            options={
                'db_table': 'tbl_data_trans',
            },
        ),
    ]
