# Generated by Django 3.1.7 on 2021-07-18 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal_in_tb', '0008_auto_20210718_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltransaction',
            name='id_item',
            field=models.ForeignKey(blank=True, db_column='id_item', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='deal_in_tb.tblitem'),
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='api_key',
            field=models.CharField(default='uzoOIok0ZjG1sddxAwylhuBVDIWUS89iihSRNxEOBjTVuhJlum', max_length=50),
        ),
        migrations.DeleteModel(
            name='TblDataTrans',
        ),
    ]
