# Generated by Django 3.1.7 on 2021-07-18 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_in_tb', '0009_auto_20210718_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltransaction',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='api_key',
            field=models.CharField(default='xqCJGL54hHGnWMwKhZfvYRuQsDXMBt5B9bNI1TKo2zuiBwiTeS', max_length=50),
        ),
    ]
