# Generated by Django 3.1.7 on 2021-11-14 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal_in_tb', '0011_auto_20210718_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser',
            name='api_key',
            field=models.CharField(default='VQ8D76npn5iKIXMXFtJ9evkaWp2L1SEvJGFFRrTFpIwYRfPz9I', max_length=50),
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='id_role',
            field=models.ForeignKey(db_column='id_role', default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='deal_in_tb.tblrole'),
        ),
    ]
