# Generated by Django 3.1.7 on 2021-11-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_in_tb', '0013_auto_20211120_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbluser',
            name='limited',
        ),
        migrations.AddField(
            model_name='tblstore',
            name='limited',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tblstore',
            name='api_key',
            field=models.CharField(default='q61NPCXKi9cGMiBrVCD4YFIZ8eieJ7xg1u2LsGzN0IXz35WEMT', max_length=50),
        ),
    ]
