# Generated by Django 3.1.7 on 2021-11-30 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal_in_tb', '0014_auto_20211120_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbltransaction',
            name='id_item',
        ),
        migrations.AddField(
            model_name='tblcart',
            name='id_transaction',
            field=models.ForeignKey(blank=True, db_column='id_transaction', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='deal_in_tb.tbltransaction'),
        ),
        migrations.AlterField(
            model_name='tblstore',
            name='api_key',
            field=models.CharField(default='Zs8sAzl245s4VWPSdhfm0QioZVOixK6MsRKIzhFGVNoRckOZ7k', max_length=50),
        ),
    ]
