# Generated by Django 3.1.7 on 2021-11-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_in_tb', '0015_auto_20211130_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbltransaction',
            name='description',
        ),
        migrations.AlterField(
            model_name='tblstore',
            name='api_key',
            field=models.CharField(default='dFlGYTd3ZLRzJKC5JxxAzZuLfEKSqOKoqQMLxaHMRoc8c2xurB', max_length=50),
        ),
    ]
