# Generated by Django 3.1.7 on 2021-12-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_in_tb', '0016_auto_20211130_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcart',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tblstore',
            name='api_key',
            field=models.CharField(default='RoreQcmCyovXXtHidZkSzUkn06zUPNT1QjYECnOJTG7CpwgDZ7', max_length=50),
        ),
    ]
