# Generated by Django 3.1.7 on 2021-12-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_in_tb', '0017_auto_20211203_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcart',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tblstore',
            name='api_key',
            field=models.CharField(default='758wtHwweEjrBQjp0k1mSyrPhqZ6gaqxwzhrUFpKUrAAtUKHwc', max_length=50),
        ),
    ]
