# Generated by Django 3.1.7 on 2022-02-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_in_tb', '0019_auto_20220211_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltransaction',
            name='token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tblstore',
            name='api_key',
            field=models.CharField(default='2TB4LakuTI4YfToEtGnMWiZq0h4t8Lam9qeBfAUHx76igkOZvx', max_length=50),
        ),
    ]
